# 端口
server:
    port: 8080

# 应用名称
spring:
    application:
        name: ashe-oauth
    # 数据库配置
    datasource:
        # .cj适配mysql6以上版本，因目前本地mysql版本为8
        driver-class-name: com.mysql.cj.jdbc.Driver
        # draft为指定的数据库database
        url: jdbc:mysql://localhost:3306/draft?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    # redis 配置
    redis:
        # 地址       默认：127.0.0.1
        host: localhost
        # 端口       默认为6379
        port: 6379
        # 数据库索引  使用索引为0的数据库
        database: 0
        # 密码 默认无
        password:
        # 连接超时时间
        timeout: 10s
        #   与Jedis相比，lettuce 则完全克服了其线程不安全的缺点.
        #   lettuce 是一个可伸缩的线程安全的Redis客户端，支持同步、异步和响应式模式。
        #   多个线程可以共享一个连接实例， 而不必担心多线程并发问题。
        #   它基于优秀Netty NIO框架构建，支持Redis的更多高级功能。
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms

mybatis-plus:
    configuration:
        # json 格式 键的值为null,返回属性
        call-setters-on-nulls: true
        map-underscore-to-camel-case: true
        # 解决null值问题导致的jdbcTypeException
        jdbc-type-for-null: "null"
    global-config:
        db-config:
            # 更新策略 忽略NULL 不更新的问题
            update-strategy: IGNORED
    # 扫描 *Mapper.xml 路径
    mapper-locations: classpath:/mapper/**.xml




